title: テストに使えるツイートリスト
email: mitsuru793@gmail.com
description: >
  テストに使えるツイートを作成しました。
baseurl: "sample-tweets"
url: ""
twitter_username: mitsuru793
github_username:  mitsuru793

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
